name: Github CI & Docker build and push

on:
  push:
    branches: [ main ]
  pull-request:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubunut-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: login with docker cred
        uses: docker/login-action@v5
        with: 
          username: {{ secrets.DOCKER_USER }}
          password: {{ secrets.DOCKER_PASS }}
      - name: build the docker image
        run : 'docker build -t $DOCKER_USER/flask-app:latest'
      
      - name: push the docker image
        run : 'docker push $DOCKER_USER/flask-app:latest'
      